apiVersion: v1
kind: Service
metadata:
  name: contentredis-service
spec:
  selector:
    app: contentredis-service
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer

