apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
spec:
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
        - name: content-service
          image: artemstolb/brightnight-content:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
      hostname: contentservice
      restartPolicy: Always